### ISSUE TITLE
Project layout and namespace

### ISSUE THREAD

**Issue by simgreci** [simgreci/SQLXEtoEventHub#12]
I propose a new layout of the project and better organize namespaces:

1 project called xetohub
Inside the project different folders
core -> map xetohub.core namespace -> core classes, include code inside SQLXEtoEventHubLib
(and inheriting existing namespaces)
sql -> map xetohub.sql namespace -> sqlclr code, indclude SQLXEtoEventHubSp

1 project called xetohub.test
test -> map xetohub.test namespace -> unit testing

1 project called xetohub.cmd
cmd .> map xetohub.cmd namespace -> command line utility

**Comment by simgreci** [comment]
New project layout and namespace inside vnext branch. @MindFlavor please review and if you agree we can pull request new version 0.0.2.0.

**Comment by MindFlavor** [comment]
Definitely better. 
:+1:
