### ISSUE TITLE
Persistency for LastFile and Offset

### ISSUE THREAD

**Issue by simgreci** [simgreci/SQLXEtoEventHub#6]
Currently for every XE Trace an offset and a lastfile are saved inside the registry. This may conflict in case of a clustered instance.

**Comment by MindFlavor** [comment]
We might use the a small table in MSDB

**Comment by MindFlavor** [comment]
Scratch that, as suggested by MatteoTe we should probably provision a new database. We will need it for loading the SQLCLR dll anyway. A simple table will suffice.

We also need a setup script.

**Comment by simgreci** [comment]
SqlStore.cs has been implemented and tested. Now the sqlclr stored procedure save last file and offset inside a database table.
