### ISSUE TITLE
Clean up System.Web dependencies

### ISSUE THREAD

**Issue by MindFlavor** [simgreci/SQLXEtoEventHub#9]
Required as per issue #8.

**Comment by MindFlavor** [comment]
This must be tested (I haven't tried to import the SQLCLR dll) but the `System.Web` dll is no longer used since [https://github.com/simgreci/SQLXEtoEventHub/commit/7f25ad882d154167e0afc933b2faa69a963d5459](https://github.com/simgreci/SQLXEtoEventHub/commit/7f25ad882d154167e0afc933b2faa69a963d5459)

**Comment by simgreci** [comment]
Great Job Francesco, i make changes to the SQLCLR stored procedure code and test it.

**Comment by simgreci** [comment]
Dependency graph for xetohub clr stored procedure still resolve System.Web :-(

```
Msg 10301, Level 16, State 1, Line 1
Assembly 'SQLXEtoEventHubSp' references assembly 'system.web, version=4.0.0.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a.', which is not present in the current database. SQL Server attempted to locate and automatically load the referenced assembly from the same location where referring assembly came from, but that operation has failed (reason: 2(The system cannot find the file specified.)). Please load the referenced assembly into the current database and retry your request.
```

**Comment by simgreci** [comment]
I've cleaned on system.web reference removing log4net dependency be1ae9a. Continue to work on other issue:
Assembly 'SQLXEtoEventHubSp' references assembly 'system.runtime.serialization,
